// 
//  Profile.m
//  recon
//
//  Created by Sumanth Peddamatham on 8/5/09.
//  Copyright 2009 __MyCompanyName__. All rights reserved.
//

#import "Profile.h"

#import "Session.h"

@implementation Profile 

@dynamic scanDelayString;
@dynamic icmpTimeStamp;
@dynamic debuggingLevel;
@dynamic maxParallelismString;
@dynamic minParallelism;
@dynamic setSourcePortString;
@dynamic scanRandomString;
@dynamic scriptArgs;
@dynamic dontPing;
@dynamic minHostgroup;
@dynamic ftpBounceString;
@dynamic maxTimeToScan;
@dynamic scriptScan;
@dynamic maxProbeTimeout;
@dynamic initialRttTimeout;
@dynamic synPingString;
@dynamic maxOutstandingProbes;
@dynamic targetListString;
@dynamic idleScan;
@dynamic scanRandom;
@dynamic excludeFile;
@dynamic enableAggressive;
@dynamic initialRttTimeoutString;
@dynamic scriptsToRun;
@dynamic excludeHosts;
@dynamic sessionTarget;
@dynamic minHostsParallel;
@dynamic minHostsParallelString;
@dynamic maxTimeToScanString;
@dynamic debuggingLevelString;
@dynamic ipv6Support;
@dynamic synPing;
@dynamic maxHostgroup;
@dynamic versionDetection;
@dynamic verbosity;
@dynamic minOutstandingProbesString;
@dynamic hostTimeout;
@dynamic initialProbeTimeout;
@dynamic useDecoysString;
@dynamic minDelayBetweenProbes;
@dynamic setIPv4TTLString;
@dynamic traceRoute;
@dynamic idleScanString;
@dynamic udpProbe;
@dynamic minProbeTimeoutString;
@dynamic maxHostsParallelString;
@dynamic setSourceIPString;
@dynamic portsToScan;
@dynamic osDetection;
@dynamic fragmentIP;
@dynamic maxRetries;
@dynamic initialProbeTimeoutString;
@dynamic maxScanDelay;
@dynamic excludeHostsString;
@dynamic minHostgroupString;
@dynamic maxParallelism;
@dynamic maxScanDelayString;
@dynamic name;
@dynamic traceScript;
@dynamic maxRttTimeoutString;
@dynamic portsToScanString;
@dynamic minParallelismString;
@dynamic scanDelay;
@dynamic minOutstandingProbes;
@dynamic minDelayBetweenProbesString;
@dynamic isEnabled;
@dynamic ackPingString;
@dynamic fastScan;
@dynamic setSourcePort;
@dynamic setNetworkInterfaceString;
@dynamic ipprotoProbe;
@dynamic maxRetriesString;
@dynamic maxHostsParallel;
@dynamic maxRttTimeout;
@dynamic hostTimeoutString;
@dynamic scriptsToRunString;
@dynamic scriptArgsString;
@dynamic maxOutstandingProbesString;
@dynamic minProbeTimeout;
@dynamic excludeFileString;
@dynamic tcpScanTag;
@dynamic timingTemplateTag;
@dynamic minRttTimeout;
@dynamic icmpNetmask;
@dynamic packetTrace;
@dynamic maxHostgroupString;
@dynamic targetList;
@dynamic minRttTimeoutString;
@dynamic icmpPing;
@dynamic ftpBounce;
@dynamic udpProbeString;
@dynamic nonTcpScanTag;
@dynamic setIPv4TTL;
@dynamic defaultPing;
@dynamic ipprotoProbeString;
@dynamic setSourceIP;
@dynamic verbosityString;
@dynamic ackPing;
@dynamic extraOptionsString;
@dynamic maxProbeTimeoutString;
@dynamic disableReverseDNS;
@dynamic useDecoys;
@dynamic disableRandom;
@dynamic extraOptions;
@dynamic setNetworkInterface;
@dynamic sessions;
@dynamic children;
@dynamic parent;

@end
